### ISSUE TITLE
Translation ignored

### ISSUE THREAD

**Issue by AureliusHogan** [KaufmannDigital/KaufmannDigital.CookieConsent#11]
The text in the div.cc-revoke is not taken from translation. This text is currently a fixed string in the js file. 

It would be nice if you change this in a next version.

Besides that: **cool**!

**Comment by Nikdro** [comment]
Thanks for your issue 🙂 
I'll have a look on it tomorrow. 

But if you are interested in a more advanced and more DSGVO-friendly Package, have a look at https://github.com/KaufmannDigital/KaufmannDigital.GDPR.CookieConsent/

**Comment by Nikdro** [comment]
Added that in version 1.5.3. You can now change that label via Translation-File, as all other labels!
