### ISSUE TITLE
NodeUri trows an exception. It must be Neos.Neos:NodeUri

### ISSUE THREAD

**Issue by beardcoder** [KaufmannDigital/KaufmannDigital.CookieConsent#6]
https://github.com/KaufmannDigital/KaufmannDigital.CookieConsent/blob/b0036d97c7c418181122517f09714d5abdb48298/Resources/Private/Fusion/Root.fusion#L22

**Comment by Nikdro** [comment]
Hello @beardcoder,

thank you for reporting this Bug. 

`NodeUri` was working under Neos 3.3, but not under Neos 4.X.
I corrected it as you recommended in 943b8a329ae44aa81a3a9ddc163a3f8e10effcfd

Thanks again!
